### PR TITLE
midproject

### PR DESCRIPTION
**Pull request by yzelac**
created src/download_data.py;
created src/upload_data.py;
created src/sql/sqldb.py;

All functions have been tested. The new "Wine_Predict" table is within the "msia423" database on RDS.

### CODE REVIEW

**Comment by yfeng46** [comment]
Hey Yucheng, could you please provide a requirements.txt file for the environment to run your code?

**Comment by yzelac** [comment]
Hi Joyce, good catch! The requirements.txt is uploaded. Feel free to use Python 3.7 for the virtual environment.

**Comment by yfeng46** [comment]
Could you please clarify a bit about the running process of your code in README?

**Comment by yzelac** [comment]
The READ.Me is updated now.

**Comment by yfeng46** [comment]
For the download.py, I think you need to remove the .. in the Save path or to ask user run your code inside the src folder. Otherwise there is going to be some problem.

**Comment by yzelac** [comment]
Thank you. Path in relevant filed are edited.

**Comment by yfeng46** [comment]
I run all the codes now and I think it looks good!

**Comment by yfeng46** [comment]
Functionality:
The codes are doing what they supposed to do

Readability and code quality:
Codes are fairly easy to read with minimal redundancy

Overall design:
At this point of the time, the design works efficiently. Functions are modular and expandable. Some change in the code might be needed if there are more than one database is involved.

Test:
With the improvements done above, the test of the code is easier.

Documentation:
More documentation about the code as well as the logger need to be added to the function, such as the purpose of the function and the definition of the parameters. Though now the code is easy to read and understand, as more coding added, the documentation will be crucial.

**Comment by yzelac** [comment]
Thanks for the useful feedback! Logging function and docstrings are now added.

**Pull request merged**
